# Generated by Django 3.1.3 on 2020-11-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interest',
            field=models.ManyToManyField(blank=True, to='accounts.UserInterest'),
        ),
    ]
