# Generated by Django 3.1.3 on 2020-11-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='interest',
            new_name='interests',
        ),
    ]
